# docker-compose.yml
version: '3.9'

services:

  redis:
    image: "redis:latest" # Uses the official Redis image from Docker Hub
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_internal_network
  
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    # restart: unless-stopped
    env_file:
      - ./.env
    container_name: flask_app_container
    expose:
      - "8000" # Expose port 8000 within the Docker network, not to the host machine
    ports:
      - "8000:8000" # Opens port 8000 to host machine
    depends_on:
      - redis
    networks:
      - app_internal_network
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_reverse_proxy
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro # Mount the Nginx Configuration
    ports:
      - "80:80" # Map host port 80 to Caddy's port 80
      - "443:443" # Uncomment to enable HTTPS on port 443
    depends_on:
      - flask_app # Ensure the Flask app starts before Caddy
    networks:
      - app_internal_network

# Networks
networks:
  app_internal_network:
    driver: bridge
