# pull official base image
FROM python:3.11-slim-buster

# set work directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/

# run app with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

